<a href="https://colab.research.google.com/github/granthprofessional/python_learning/blob/main/numparray01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
a = [1,2,3,4]

In [ ]:
a

[1, 2, 3, 4]

In [ ]:
a = [1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

# 1,2 = integer numbers, 3.5 = floating value, hello = **sting**


In [ ]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

aagr hum srings le hee na to ???, uske bd float value aygi or ( 1. , 2. , 3.5)

In [ ]:
a = [1,2,3.5]
a

[1, 2, 3.5]

thts it ab ye float m convert hogya 😎


In [ ]:
np.array(a)

array([1. , 2. , 3.5])

In [ ]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array generation functons: 🎶

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros(9)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((3,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones((3,9))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,9,3)
arr

array([1., 5., 9.])

In [ ]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

random gernation functions 💁🏻

In [ ]:
np.random.rand(10)

array([0.45011692, 0.70883408, 0.75518947, 0.71099784, 0.7159012 ,
       0.95035811, 0.08264522, 0.86308655, 0.06681292, 0.9719314 ])

In [ ]:
np.random.randn(10)

array([ 0.35411087,  0.42409164,  0.59762547,  0.07406705, -0.70880027,
        0.47775903,  1.96080916,  0.94101874, -0.24239704, -1.20142383])

In [ ]:
np.random.randint(10)

5

In [ ]:
np.random.randint(10,20,15)

array([12, 15, 11, 19, 12, 16, 15, 15, 19, 18, 10, 10, 12, 15, 16])

**array attributes 🫥**

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

# array methods 💁🏻

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

**12,15,18, they are print cuz numpy print are straight value of arr🤩**

In [ ]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [ ]:
arr.mean() #45/9 isly vo print hua 5

np.float64(5.0)

In [ ]:
arr.std() #

np.float64(2.581988897471611)

**all arr vales are put in new code**

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr.min()
arr.max()
arr.sum()

np.sum(arr, axis=0)

arr.mean()

arr.std()
# Step 1: Mean = 5.0
# Step 2: (1-5)²=16, (2-5)²=9, (3-5)²=4, (4-5)²=1, (5-5)²=0, (6-5)²=1, (7-5)²=4, (8-5)²=9, (9-5)²=16
# Step 3: Sum = 16+9+4+1+0+1+4+9+16 = 60
# Step 4: 60/9 = 6.666666666666667
# Step 5: √6.666666666666667 = import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr.min()
arr.max()
arr.sum()

np.sum(arr, axis=0)

arr.mean()

arr.std()
# Step 1: Mean = 5.0
# Step 2: (1-5)²=16, (2-5)²=9, (3-5)²=4, (4-5)²=1, (5-5)²=0, (6-5)²=1, (7-5)²=4, (8-5)²=9, (9-5)²=16
# Step 3: Sum = 16+9+4+1+0+1+4+9+16 = 60
# Step 4: 60/9 = 6.666666666666667
# Step 5: √6.666666666666667 = 2.581988897471611
#then the value are 2.581988897471611

np.float64(2.581988897471611)

In [ ]:
arr.argmax()
# isme max index aa jayega 8

np.int64(8)

In [ ]:
arr.argmin()
#isme min value aa jaygi 0

np.int64(0)

**reshaping, resizing💁🏻**

In [ ]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(6,5)

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])